import type { NextPage } from 'next'
import Head from 'next/head'
import { Card, Text, Metric, Flex, ProgressBar } from "@tremor/react";
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Next.js + Tremor UI!</a>
        </h1>

        <Card maxWidth="max-w-sm" marginTop='mt-10'>
          <Text>Sales</Text>
          <Metric>$ 71,465</Metric>
          <Flex marginTop='mt-4'>
              <Text>32% of annual target</Text>
              <Text>$ 225,000</Text>
          </Flex>
          <ProgressBar percentageValue={ 32 } marginTop="mt-2" />
        </Card>

      </main>
    </div>
  )
}

export default Home
